@startuml
left to right direction
:user:
:keyboard:
:display:
package "Z80 FPGA" as z80 {
        usecase "Boot the Z80" as boot_use
        usecase "Interact with loaded program" as interact_use
        usecase "Execute instructions from memory" as execute_system
        usecase "Capture input from keyboard subsystem" as cinput
        usecase "Display text" as dout
        usecase "Run program in memory" as load
        usecase "Load program from SD card into memory" as load_sd
        usecase "Initialize memory with program" as load_rom
}
:user: -- boot_use
:user: -- interact_use
interact_use ..> cinput : <<include>>
interact_use ..> dout : <<include>>
interact_use ..> execute_system : <<include>>
boot_use ..> load : <<include>>
load <. load_rom : <<extend>>
load <. load_sd : <<extend>>
cinput -- :keyboard:
dout -- :display:
@enduml
