@startuml
left to right direction
:user:
package "Z80 FPGA" as z80 {
        usecase "Interact with loaded program" as interact_use
        usecase "Capture input" as cinput
        usecase "Display text" as dout
        usecase "Load a program" as load
        usecase "Load program from SD card into memory" as load_sd
        usecase "Load program from ROM into memory" as load_rom
}
:user: -- cinput
interact_use ..> cinput : <<include>>
interact_use ..> dout : <<include>>
interact_use ..> load : <<include>>
load <.. load_rom : <<extend>>
load <.. load_sd : <<extend>>
@enduml
