@startuml
frame "Emulated Zilog Z80 Hardware architecture" {
        node "Zybo Z7"  {
                component "Z80 soft core" as z80_sc
                component "Display adapter" as display_adpt
                component "keyboard adapter" as keyboard_adpt
                component "target program" as program
                z80_sc -- display_adpt
                z80_sc -- keyboard_adpt
                z80_sc ..> program : Loaded at boot
        }
        node "USB keyboard" as keyboard
        component "Zybo Z7 to RCA adapter" as rca_adpt
        node "Retro display" as display

        keyboard_adpt -(0- keyboard
        display_adpt -(0- rca_adpt
        rca_adpt -- display
}
@enduml
