@startuml
frame "Emulated Zilog Z80 Deployment" {
        node "Zybo Z7"  {
                component "Z80 soft core" as z80_sc
                component "UART adapter" as uart_adpt
                z80_sc -- uart_adpt
        }
        node "Compiler System" {
                file "Target program source code" as program_source
                component "z88dk" as compiler
                component "IO Hooks" as hooks

                compiler ..> program_source : Takes source as input
                compiler ..> hooks : Uses hooks for IO handling
        }
        node "Host machine" {
                component putty
        }
        node "Xilinx Vivado" as vivado
        artifact "target program" as program
        file "Z80 design source" as z80_src
        uart_adpt -(0- putty
        compiler <. program : Compiler constructs runnable binary
        vivado ..> program : Loads program with Z80 design
        vivado ..> z80_src
        z80_sc .> vivado
}
@enduml
