@startgantt
Project starts 2026-01-01
[Presentation] happens at 2026-04-11
[Z80 Softcore] starts D+0 and ends 2026-04-01
[Softcore Complete] happens at [Z80 Softcore]'s end
[Load the Adventure game] ends 2026-04-11
[Playing the Adventure game] happens at [Load the Adventure game]'s end
-- Tasks --
[Datapath] starts D+3 and requires 60 days
[ALU] on {Bach} starts at [Datapath]'s start and ends 2026-01-31
[Register file] on {Kieran} starts at [Datapath]'s start and ends 2026-01-31
[Datapath Top level architecture] ends at [Datapath]'s end
[Completed Datapath] happens at [Datapath]'s end
@endgantt
